# docker-compose.yml
version: '3.8'

services:
  app:
    container_name: bot-borz
    image: bot-borz
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    networks:
      - net
    volumes:
      - ./src:/usr/src/app/src

  prometheus:
    image: prom/prometheus:latest
    depends_on:
      - app
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - net

  grafana:
    image: grafana/grafana:latest
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    user: "${UID}:${GID}"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - net

volumes:
  prometheus_data: {}

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.220.0/24