# docker-compose.yml
version: '3.8'

services:
  app:
    container_name: bot-borz
    image: bot-borz
    build: .
    ports:
      - 6000:6000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    networks:
      - net
    volumes:
      - ./src:/usr/src/app/src

  prometheus:
    depends_on:
      - app
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - net

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana
    user: "1000"
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    networks:
      - net

volumes:
  prometheus_data: {}

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.220.0/24